version: '3'

services:
  httpd:
    container_name: httpd
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 80:80
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    networks:
      - net1
  db:
    container_name: db
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    networks:
      - net1
    ports:
      - 3306:3306
networks:
  net1:
